/**
 * 统一错误码。
 *
 * 第 2 阶段实际使用的错误码。后续阶段按 prd.md §12.13 扩充。
 */
export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  // V1.2 I1:超过 express body limit。此前 PayloadTooLargeError 不匹配任何分支 → 误落 500
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",

  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  CONVERSATION_DELETED: "CONVERSATION_DELETED",
  CONVERSATION_ARCHIVED: "CONVERSATION_ARCHIVED",
  CONVERSATION_REQUEST_IN_PROGRESS: "CONVERSATION_REQUEST_IN_PROGRESS",

  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",

  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  // prd §12.1:启动时残留的 PROCESSING 无法确认 Prompt 是否已提交给 Gemini,强制 FAILED 且禁止重发
  SERVER_RESTARTED_DURING_PROCESSING: "SERVER_RESTARTED_DURING_PROCESSING",
  // prd §12.1:残留 CANCELLING 同样无法确认 Gemini 是否真的停了,强制 FAILED 且禁止重发
  SERVER_RESTARTED_DURING_CANCELLING: "SERVER_RESTARTED_DURING_CANCELLING",
  // prd §8.9:Cancel 只对 PENDING / PROCESSING / CANCELLING 合法,已终态的 Request 不可取消
  REQUEST_NOT_CANCELLABLE: "REQUEST_NOT_CANCELLABLE",
  // 第 6 阶段:流式内容写库失败 → 整次执行按 FAILED 收尾;SSE 连接自身故障(只影响该连接)
  STREAMING_UPDATE_FAILED: "STREAMING_UPDATE_FAILED",
  SSE_CONNECTION_ERROR: "SSE_CONNECTION_ERROR",

  PROVIDER_NOT_READY: "PROVIDER_NOT_READY",
  PROVIDER_LOGIN_REQUIRED: "PROVIDER_LOGIN_REQUIRED",
  PROVIDER_PROFILE_IN_USE: "PROVIDER_PROFILE_IN_USE",
  PROVIDER_BROWSER_START_FAILED: "PROVIDER_BROWSER_START_FAILED",
  PROVIDER_PAGE_CLOSED: "PROVIDER_PAGE_CLOSED",
  // prd §12.2/§12.13:Chromium 进程 / Context / renderer 崩溃统一用这一个码。
  // 原 PROVIDER_PAGE_CRASHED 已并入此处:一进程 = 一 context = 一 page,两者可观测后果等价,
  // 而 prd 清单里只有 BROWSER_CRASHED。具体是哪种崩溃由日志的 fault 字段区分。
  PROVIDER_BROWSER_CRASHED: "PROVIDER_BROWSER_CRASHED",
  PROVIDER_NAVIGATION_FAILED: "PROVIDER_NAVIGATION_FAILED",
  PROVIDER_DOM_CHANGED: "PROVIDER_DOM_CHANGED",
  PROVIDER_RESPONSE_TIMEOUT: "PROVIDER_RESPONSE_TIMEOUT",
  PROVIDER_CONVERSATION_UNAVAILABLE: "PROVIDER_CONVERSATION_UNAVAILABLE",
  // prd §11.3:已调用 Gemini stop 但在超时内无法确认真的停了 → 本次 Request 判 FAILED,
  // 随后 Browser Manager 重建 Page/Context,Scheduler 暂停到 Provider 重新 READY
  PROVIDER_CANCELLATION_UNCONFIRMED: "PROVIDER_CANCELLATION_UNCONFIRMED",
  // prd §12.13 清单内;限流判据依赖第 5 阶段 Scheduler 的失败分类,暂无抛出点
  PROVIDER_RATE_LIMITED: "PROVIDER_RATE_LIMITED",
  // M1:请求的模型键不在 provider 模型目录中(目录读取成功但无此键)
  PROVIDER_MODEL_UNAVAILABLE: "PROVIDER_MODEL_UNAVAILABLE",
  // M1:读取模型目录 / 切换模型失败(页面未就绪、DOM 变更、菜单操作失败等)
  PROVIDER_MODEL_SWITCH_FAILED: "PROVIDER_MODEL_SWITCH_FAILED",

  // V1.2 I1 附件契约(请求侧)
  // 单图 >5MB / 总量 >10MB / 张数 >4
  ATTACHMENT_TOO_LARGE: "ATTACHMENT_TOO_LARGE",
  // dataURL 前缀 MIME 与真实 magic byte 不一致,或类型不在白名单
  UNSUPPORTED_ATTACHMENT_TYPE: "UNSUPPORTED_ATTACHMENT_TYPE",
  // AttachmentStore 内存配额不足:入口拒绝,绝不淘汰已在队列里的附件(I0.1 §3.4)
  ATTACHMENT_CAPACITY_EXCEEDED: "ATTACHMENT_CAPACITY_EXCEEDED",
  // V1.2 I1 登记、I2-B 抛出:附件注入/等待就绪失败。份数断言(claim 后 take 缺或份数不符)
  // 也在 Executor 之前用它,保证「绝不降级成只发文字」
  PROVIDER_ATTACHMENT_FAILED: "PROVIDER_ATTACHMENT_FAILED",
  PROVIDER_ATTACHMENT_TIMEOUT: "PROVIDER_ATTACHMENT_TIMEOUT",

  // 浏览器状态 API(docs/browser-status-api.md:GET /api/browser/status + POST /restart)
  BROWSER_RESTART_CONFLICT: "BROWSER_RESTART_CONFLICT",
  BROWSER_LAUNCH_FAILED: "BROWSER_LAUNCH_FAILED",
  BROWSER_RESTART_FAILED: "BROWSER_RESTART_FAILED",
  BROWSER_RESTART_TIMEOUT: "BROWSER_RESTART_TIMEOUT",

  // SEC-1 服务端鉴权(docs/SEC1_AUTH_DESIGN.md §十三)
  // 未认证访问受保护资源;凭据错误;登录限流;CSRF Origin 校验拒绝
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_RATE_LIMITED: "AUTH_RATE_LIMITED",
  AUTH_CSRF_REJECTED: "AUTH_CSRF_REJECTED",

  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
