import type { ErrorCode } from "./error-codes.js";

/**
 * 错误码 → HTTP 状态码的唯一映射(第 9 阶段 §六)。
 *
 * 任何地方(Controller / Service / 错误出口)都不得自行决定错误响应的 HTTP 状态:
 * AppError 的 statusCode 一律由此表推导。新增错误码时必须在此登记,
 * 漏登记会在类型检查期报错(Record<ErrorCode, number> 强制全覆盖)。
 */
export const ERROR_CODE_HTTP_STATUS = {
  // 请求本身不合法
  VALIDATION_ERROR: 400,
  // body 超过 express limit(I0.1 §1.3:修此前一律落 500 的既有缺陷)
  PAYLOAD_TOO_LARGE: 413,

  // 会话资源
  CONVERSATION_NOT_FOUND: 404,
  CONVERSATION_DELETED: 409,
  CONVERSATION_ARCHIVED: 409,
  CONVERSATION_REQUEST_IN_PROGRESS: 409,

  // V1.2 附件契约(请求侧)
  ATTACHMENT_TOO_LARGE: 413,
  UNSUPPORTED_ATTACHMENT_TYPE: 415,
  ATTACHMENT_CAPACITY_EXCEEDED: 503,

  // Request 生命周期
  IDEMPOTENCY_KEY_REUSED: 409,
  REQUEST_NOT_FOUND: 404,
  REQUEST_NOT_CANCELLABLE: 409,
  SERVER_RESTARTED_DURING_PROCESSING: 500,
  SERVER_RESTARTED_DURING_CANCELLING: 500,
  STREAMING_UPDATE_FAILED: 500,
  SSE_CONNECTION_ERROR: 500,

  // Provider(自动化)侧
  PROVIDER_NOT_READY: 500,
  PROVIDER_LOGIN_REQUIRED: 401,
  PROVIDER_PROFILE_IN_USE: 500,
  PROVIDER_BROWSER_START_FAILED: 500,
  PROVIDER_PAGE_CLOSED: 500,
  PROVIDER_BROWSER_CRASHED: 500,
  PROVIDER_NAVIGATION_FAILED: 500,
  PROVIDER_DOM_CHANGED: 500,
  PROVIDER_RESPONSE_TIMEOUT: 500,
  PROVIDER_CONVERSATION_UNAVAILABLE: 409,
  PROVIDER_CANCELLATION_UNCONFIRMED: 500,
  PROVIDER_RATE_LIMITED: 429,
  // M1:模型键不在目录中 → 客户端可换一个键重试,与「会话不可用」同级冲突
  PROVIDER_MODEL_UNAVAILABLE: 409,
  // M1:目录读取 / 模型切换失败 → 服务端内部自动化故障
  PROVIDER_MODEL_SWITCH_FAILED: 500,
  // V1.2:I1 的份数断言用 FAILED;TIMEOUT 留给 I2-B 的附件就绪等待上限
  PROVIDER_ATTACHMENT_FAILED: 502,
  PROVIDER_ATTACHMENT_TIMEOUT: 504,

  // 浏览器状态 API:重启冲突 409;启动失败 500;其他重启失败 500;超时 504
  BROWSER_RESTART_CONFLICT: 409,
  BROWSER_LAUNCH_FAILED: 500,
  BROWSER_RESTART_FAILED: 500,
  BROWSER_RESTART_TIMEOUT: 504,

  // SEC-1 鉴权:未认证 401;凭据错误 401;登录限流 429;Origin 校验拒绝 403
  AUTH_REQUIRED: 401,
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_RATE_LIMITED: 429,
  AUTH_CSRF_REJECTED: 403,

  // 兜底
  DATABASE_ERROR: 500,
  INTERNAL_ERROR: 500,
} as const satisfies Record<ErrorCode, number>;

/** 按错误码查 HTTP 状态;未知码防御性回落 500(正常情况下类型系统已保证全覆盖) */
export function httpStatusForCode(code: ErrorCode): number {
  return ERROR_CODE_HTTP_STATUS[code] ?? 500;
}
