/**
 * 统一错误码。
 *
 * 第 2 阶段实际使用的错误码。后续阶段按 prd.md §12.13 扩充。
 */
export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  CONVERSATION_DELETED: "CONVERSATION_DELETED",
  CONVERSATION_ARCHIVED: "CONVERSATION_ARCHIVED",
  CONVERSATION_REQUEST_IN_PROGRESS: "CONVERSATION_REQUEST_IN_PROGRESS",

  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",

  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
  // prd §12.1:启动时残留的 PROCESSING 无法确认 Prompt 是否已提交给 Gemini,强制 FAILED 且禁止重发
  SERVER_RESTARTED_DURING_PROCESSING: "SERVER_RESTARTED_DURING_PROCESSING",

  PROVIDER_NOT_READY: "PROVIDER_NOT_READY",
  PROVIDER_LOGIN_REQUIRED: "PROVIDER_LOGIN_REQUIRED",
  PROVIDER_PROFILE_IN_USE: "PROVIDER_PROFILE_IN_USE",
  PROVIDER_BROWSER_START_FAILED: "PROVIDER_BROWSER_START_FAILED",
  PROVIDER_PAGE_CLOSED: "PROVIDER_PAGE_CLOSED",
  PROVIDER_PAGE_CRASHED: "PROVIDER_PAGE_CRASHED",
  PROVIDER_NAVIGATION_FAILED: "PROVIDER_NAVIGATION_FAILED",
  PROVIDER_DOM_CHANGED: "PROVIDER_DOM_CHANGED",
  PROVIDER_RESPONSE_TIMEOUT: "PROVIDER_RESPONSE_TIMEOUT",
  PROVIDER_CONVERSATION_UNAVAILABLE: "PROVIDER_CONVERSATION_UNAVAILABLE",
  // prd §12.13 清单内;限流判据依赖第 5 阶段 Scheduler 的失败分类,暂无抛出点
  PROVIDER_RATE_LIMITED: "PROVIDER_RATE_LIMITED",

  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
