/**
 * 统一错误码。
 *
 * 第 2 阶段实际使用的错误码。后续阶段按 prd.md §12.13 扩充。
 */
export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  CONVERSATION_DELETED: "CONVERSATION_DELETED",
  CONVERSATION_ARCHIVED: "CONVERSATION_ARCHIVED",
  CONVERSATION_REQUEST_IN_PROGRESS: "CONVERSATION_REQUEST_IN_PROGRESS",

  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",

  REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",

  PROVIDER_NOT_READY: "PROVIDER_NOT_READY",
  PROVIDER_LOGIN_REQUIRED: "PROVIDER_LOGIN_REQUIRED",
  PROVIDER_PROFILE_IN_USE: "PROVIDER_PROFILE_IN_USE",
  PROVIDER_BROWSER_START_FAILED: "PROVIDER_BROWSER_START_FAILED",
  PROVIDER_PAGE_CLOSED: "PROVIDER_PAGE_CLOSED",
  PROVIDER_PAGE_CRASHED: "PROVIDER_PAGE_CRASHED",
  PROVIDER_NAVIGATION_FAILED: "PROVIDER_NAVIGATION_FAILED",

  DATABASE_ERROR: "DATABASE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
